package com.example.cameron.fordapp;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.BaseAdapter;
import android.widget.TextView;

import java.util.ArrayList;

/**
 * Created by Cameron on 11/29/2016.
 *
 * The LogsAdapter class lists all of the logs generated by the application based on the current
 * drive of the user.
 *
 */
public class LogsAdapter extends BaseAdapter {

    /**
     * Context of the LogsAdapter
     */
    private Context mContext;

    /**
     * LayoutInflater of the LogsAdapter to create objects for View
     */
    private static LayoutInflater mInflater;

    /**
     * List of the logs currently in the adapter
     */
    private ArrayList<Log> logList;

    /**
     * Public constructor of the LogsAdapter
     *
     * @param context
     */
    public LogsAdapter(Context context) {
        mContext = context;
        mInflater = LayoutInflater.from(mContext);
        logList = new ArrayList<Log>();
    }

    /**
     * Adds a new Log to the adapter and updates the view
     *
     * @param data
     */
    public void add(Log data) {
        logList.add(data);
        notifyDataSetChanged();
    }

    /**
     * Clears the adapter of all Logs and updates the view
     */
    public void clear() {
        logList.clear();
        notifyDataSetChanged();
    }

    @Override
    public int getCount() {
        return logList.size();
    }

    @Override
    public Object getItem(int position) {
        return logList.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent){
        convertView = mInflater.inflate(R.layout.log_layout, null);

        TextView logDate = (TextView) convertView.findViewById(R.id.log_date);
        TextView logViolation = (TextView) convertView.findViewById(R.id.log_violation);
        TextView speed = (TextView) convertView.findViewById(R.id.log_speed);

        Log log = logList.get(position);

        logDate.setText("Date: " + log.getDate().toString());
        logViolation.setText("Violation: " + log.getViolation());
        speed.setText("Speed: " + log.getSpeed());

        return convertView;
    }

}
